"""cx_Freeze build configuration for openstan.

Usage (run from the repository root with the uv-managed venv active):

    uv run python cx_freeze_setup.py build          # frozen directory
    uv run python cx_freeze_setup.py bdist_msi      # Windows MSI installer
    uv run python cx_freeze_setup.py bdist_dmg      # macOS disk image
    uv run python cx_freeze_setup.py bdist_deb      # Linux Debian package
    uv run python cx_freeze_setup.py bdist_rpm      # Linux RPM package

The CI release workflow (`.github/workflows/release.yml`) calls the appropriate
target on each platform runner automatically.

Notes
-----
* Python 3.14 is explicitly supported by cx_Freeze 8.x.
* All Qt plugins (SQL, SVG, platform) are pulled in via the ``pyqt6`` hook that
  ships with cx_Freeze.  If any plugin is missing at runtime, add it to the
  ``zip_include_packages`` exclusion list or via ``include_files``.
* The app icon must be pre-generated by the CI workflow before this script runs:
    - ``build/icons/openstan.ico``   (Windows, multi-resolution)
    - ``build/icons/openstan.icns``  (macOS)
  These files are *not* committed to the repository; they are produced from
  ``src/openstan/icons/icon-square.svg`` by the ``cairosvg`` step in the CI.
* The ``gui.db`` seed file bundled in ``src/openstan/data/`` is included so
  that first-run database bootstrapping works without network access.
"""

from __future__ import annotations

import sys
from pathlib import Path

from cx_Freeze import Executable, setup

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

HERE = Path(__file__).parent
SRC_PKG = HERE / "src" / "openstan"
BUILD_ICONS = HERE / "build" / "icons"  # generated by CI before this script runs

# ---------------------------------------------------------------------------
# Platform-specific icon and installer options
# ---------------------------------------------------------------------------

if sys.platform == "win32":
    icon_path = str(BUILD_ICONS / "openstan.ico") if BUILD_ICONS.exists() else None
    base = "gui"  # suppresses the console window on Windows (cx_Freeze 8.x name)
elif sys.platform == "darwin":
    icon_path = str(BUILD_ICONS / "openstan.icns") if BUILD_ICONS.exists() else None
    base = None
else:
    # Linux — no platform icon for the executable itself; .desktop entry handles it
    icon_path = None
    base = None

# ---------------------------------------------------------------------------
# Data files to include alongside the frozen package
# ---------------------------------------------------------------------------
# cx_Freeze automatically copies all package data (icons, fonts, sql_files,
# gui.db) into dist/openstan/lib/openstan/ via its package-data discovery.
# No manual include_files entries are needed for openstan's own assets.
#
# Only non-Python assets from *outside* the package tree (e.g. the generated
# platform icon files produced by CI) would need explicit entries here.

include_files: list[tuple[str, str]] = []

# ---------------------------------------------------------------------------
# Packages to include / optimise
# ---------------------------------------------------------------------------
# cx_Freeze auto-discovers most dependencies, but Qt plugin packages need
# explicit inclusion to ensure the platform, SQL, and SVG plugins are bundled.

packages: list[str] = [
    "openstan",
    "PyQt6",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "PyQt6.QtSql",
    "PyQt6.QtSvg",
    "PyQt6.QtSvgWidgets",
    "bank_statement_parser",
    "polars",
]

# Packages that are safe to keep inside the zip archive (not extracted to disk).
# Large pure-Python packages benefit from this; C-extension packages must be
# excluded so their .pyd/.so files remain as real files.
zip_include_packages: list[str] = ["*"]
zip_exclude_packages: list[str] = [
    "PyQt6",
    "bank_statement_parser",
    "polars",
    "openstan",
]

# ---------------------------------------------------------------------------
# Build options
# ---------------------------------------------------------------------------

build_exe_options: dict = {
    "packages": packages,
    "include_files": include_files,
    "zip_include_packages": zip_include_packages,
    "zip_exclude_packages": zip_exclude_packages,
    # Strip test directories and __pycache__ from the bundle
    "excludes": ["tkinter", "test", "unittest", "pydoc"],
    "optimize": 1,
    "build_exe": str(HERE / "dist" / "openstan"),
}

# ---------------------------------------------------------------------------
# Platform installer options
# ---------------------------------------------------------------------------

bdist_msi_options: dict = {
    "upgrade_code": "{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}",
    "add_to_path": False,
    "initial_target_dir": r"[ProgramFilesFolder]\openstan",
    "summary_data": {
        "author": "Jason Farrar",
        "comments": "Open source bank statement analysis and visualization",
    },
}

bdist_dmg_options: dict = {
    "volume_label": "openstan",
    "applications_shortcut": True,
}

# Linux packages are configured via distutils metadata; no extra options needed.

# ---------------------------------------------------------------------------
# Executable definition
# ---------------------------------------------------------------------------

executables: list[Executable] = [
    Executable(
        script=str(SRC_PKG / "__main__.py"),
        target_name="openstan",
        base=base,
        icon=icon_path,
        shortcut_name="openstan",
        shortcut_dir="DesktopFolder",
    )
]

# ---------------------------------------------------------------------------
# setup() call
# ---------------------------------------------------------------------------

# Read version from the installed package metadata at build time so we never
# have to maintain it in two places.
try:
    from importlib.metadata import version as _pkg_version

    _version = _pkg_version("openstan")
except Exception:
    _version = "0.0.0"

setup(
    name="openstan",
    version=_version,
    description="Open source bank statement analysis and visualization",
    author="Jason Farrar",
    author_email="stillwaters.technology@gmail.com",
    url="https://openstan.org",
    options={
        "build_exe": build_exe_options,
        "bdist_msi": bdist_msi_options,
        "bdist_dmg": bdist_dmg_options,
    },
    executables=executables,
)
