"""cx_Freeze build configuration for openstan.

Usage (run from the repository root with the uv-managed venv active):

    uv run python cx_freeze_setup.py build          # frozen directory
    uv run python cx_freeze_setup.py bdist_msi      # Windows MSI installer
    uv run python cx_freeze_setup.py bdist_mac      # macOS .app bundle

Linux (.deb / .rpm) and macOS (.dmg) packaging is handled by the CI release
workflow using fpm and hdiutil respectively — not by cx_Freeze bdist targets.

The CI release workflow (`.github/workflows/release.yml`) calls the appropriate
target on each platform runner automatically.

Notes
-----
* Python 3.14 is explicitly supported by cx_Freeze 8.x.
* All Qt plugins (SQL, SVG, platform) are pulled in via the ``PySide6`` hook that
   ships with cx_Freeze.  If any plugin is missing at runtime, add it to the
   ``zip_include_packages`` exclusion list or via ``include_files``.
* The app icon must be pre-generated (or will be auto-generated via Inkscape)
  before this script runs:
    - ``build/icons/openstan.ico``   (Windows, multi-resolution)
    - ``build/icons/openstan.icns``  (macOS)
    - ``build/icons/openstan.png``   (Linux — auto-generated via Inkscape if absent)
  The .ico and .icns files are *not* committed to the repository; they are
  produced from ``src/openstan/icons/icon-square.svg`` by the CI.  The PNG
  is also produced by CI but will be regenerated automatically by this script
  if build_exe is re-invoked in a temporary directory.
* The ``gui.db`` seed file bundled in ``src/openstan/data/`` is included so
  that first-run database bootstrapping works without network access.
"""

from __future__ import annotations

import importlib.util as _ilu
import shutil
import subprocess
import sys
from pathlib import Path

from cx_Freeze import Executable, setup

# ---------------------------------------------------------------------------
# Version — resolved early so platform option dicts can reference it
# ---------------------------------------------------------------------------

try:
    from importlib.metadata import version as _pkg_version

    _version = _pkg_version("openstan")
except Exception:
    _version = "0.0.0"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

HERE = Path(__file__).parent
SRC_PKG = HERE / "src" / "openstan"
BUILD_ICONS = HERE / "build" / "icons"  # generated by CI before this script runs

# ---------------------------------------------------------------------------
# Platform-specific icon and installer options
# ---------------------------------------------------------------------------

if sys.platform == "win32":
    icon_path = str(BUILD_ICONS / "openstan.ico") if BUILD_ICONS.exists() else None
    base = "gui"  # suppresses the console window on Windows (cx_Freeze 8.x name)
elif sys.platform == "darwin":
    icon_path = str(BUILD_ICONS / "openstan.icns") if BUILD_ICONS.exists() else None
    base = None
else:
    # Linux — no platform icon for the executable itself; .desktop entry handles it
    icon_path = None
    base = None

# ---------------------------------------------------------------------------
# Data files to include alongside the frozen package
# ---------------------------------------------------------------------------
# cx_Freeze auto-discovers Python sources but does NOT reliably discover
# non-Python data trees inside packages built with uv_build (which does not
# emit the setuptools SOURCES.txt/RECORD metadata that cx_Freeze's package-
# data hook reads).  We therefore list every required asset explicitly so that
# a missing file produces a loud build-time error rather than a silent runtime
# failure (missing icons, fonts, broken DB bootstrap, etc.).
#
# We also include the .desktop entry and the PNG icon so the post-install
# script can install them into /usr/share/applications and /usr/share/icons
# without needing to reach back into the source tree.

_SHARE = HERE / "packaging"
_ICON_PNG = HERE / "build" / "icons" / "openstan.png"  # generated by CI

include_files: list[tuple[str, str]] = [
    (str(_SHARE / "openstan.desktop"), "share/openstan.desktop"),
]

# ---------------------------------------------------------------------------
# Explicit openstan package data files
# ---------------------------------------------------------------------------
# cx_Freeze auto-discovers Python sources but does NOT reliably discover
# non-Python data trees inside packages built with uv_build (which does not
# emit the setuptools SOURCES.txt/RECORD metadata that cx_Freeze's package-
# data hook reads).  We therefore list every required asset explicitly so that
# a missing file produces a loud build-time error rather than a silent runtime
# failure (missing icons, fonts, broken DB bootstrap, etc.).

_PKG_DATA = SRC_PKG  # src/openstan/

_required_openstan_data: list[tuple[Path, str]] = [
    (_PKG_DATA / "icons", "lib/openstan/icons"),
    (_PKG_DATA / "data" / "fonts", "lib/openstan/data/fonts"),
    (_PKG_DATA / "data" / "sql_files", "lib/openstan/data/sql_files"),
]

for _src, _dst in _required_openstan_data:
    if not Path(_src).exists():
        raise FileNotFoundError(
            f"Required openstan data path missing from source tree: {_src}\n"
            "Ensure the repository is fully checked out before building."
        )
    include_files.append((str(_src), _dst))

# gui.db is gitignored because the local copy may contain dev/test data.
# If it is absent (always the case on CI), generate a fresh empty seed db
# using the same function the app uses at first-run bootstrap.
_gui_db_src = _PKG_DATA / "data" / "gui.db"
if not _gui_db_src.exists():
    from openstan.data.create_gui_db import create_gui_db as _create_gui_db

    _create_gui_db(_gui_db_src)
    print(f"cx_freeze_setup: generated seed gui.db at {_gui_db_src}")
include_files.append((str(_gui_db_src), "lib/openstan/data/gui.db"))

# ---------------------------------------------------------------------------
# Explicit bank_statement_parser project data files
# ---------------------------------------------------------------------------
# bank_statement_parser ships a project/ subdirectory containing TOML config
# templates and SQL files that are needed to seed the user data directory on
# first run (_seed_bsp_default_project in __main__.py).  cx_Freeze does not
# auto-discover data trees inside third-party packages; we locate the tree via
# importlib and include it explicitly.  If it is absent the build fails loudly
# here rather than silently at user runtime (all statements would fail).

_bsp_spec = _ilu.find_spec("bank_statement_parser")
if _bsp_spec is None or _bsp_spec.origin is None:
    raise RuntimeError(
        "bank_statement_parser is not installed in the active virtual environment. "
        "Run 'uv sync --no-dev' before building."
    )
_bsp_pkg_dir = Path(_bsp_spec.origin).parent
_bsp_project_dir = _bsp_pkg_dir / "project"
if not _bsp_project_dir.exists():
    raise FileNotFoundError(
        f"bank_statement_parser project data directory not found: {_bsp_project_dir}\n"
        "This directory contains config templates required for statement processing. "
        "Check that the installed version of bank_statement_parser ships this tree."
    )
include_files.append((str(_bsp_project_dir), "lib/bank_statement_parser/project"))

# On Linux CI the PNG may need to be regenerated if bdist_rpm re-invokes
# build_exe in a temporary BUILD directory where the pre-built icon is absent.
# We attempt to generate it via Inkscape, then fail loudly if that also fails.
if sys.platform != "win32" and sys.platform != "darwin":
    if not _ICON_PNG.exists():
        _svg = HERE / "src" / "openstan" / "icons" / "icon-square.svg"
        _ICON_PNG.parent.mkdir(parents=True, exist_ok=True)
        try:
            subprocess.run(
                [
                    "inkscape",
                    "--export-type=png",
                    f"--export-filename={_ICON_PNG}",
                    "--export-width=256",
                    "--export-height=256",
                    str(_svg),
                ],
                check=True,
            )
        except Exception as exc:
            raise FileNotFoundError(
                f"Icon PNG not found at {_ICON_PNG} and could not be generated "
                f"via Inkscape: {exc}"
            ) from exc
    include_files.append((str(_ICON_PNG), "share/openstan.png"))

# ---------------------------------------------------------------------------
# Packages to include / optimise
# ---------------------------------------------------------------------------
# cx_Freeze auto-discovers most dependencies, but Qt plugin packages need
# explicit inclusion to ensure the platform, SQL, and SVG plugins are bundled.

packages: list[str] = [
    "openstan",
    "PySide6",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtSql",
    "PySide6.QtSvg",
    "PySide6.QtSvgWidgets",
    "bank_statement_parser",
    "polars",
    # Force cx_Freeze to include the entire email package tree.  Without this
    # the import scanner only pulls in submodules it can statically detect,
    # leaving email.header (and others) missing from the frozen bundle on
    # macOS/Windows.  email is also in zip_exclude_packages so the submodules
    # land as real .pyc files on disk rather than inside library.zip.
    "email",
]

# Packages that are safe to keep inside the zip archive (not extracted to disk).
# Large pure-Python packages benefit from this; C-extension packages must be
# excluded so their .pyd/.so files remain as real files.
zip_include_packages: list[str] = ["*"]
zip_exclude_packages: list[str] = [
    "PySide6",
    "bank_statement_parser",
    "polars",
    "openstan",
    # stdlib packages with intra-package relative imports that break under
    # zipimport in a frozen app.  These must live as real .pyc files on disk
    # rather than inside library.zip so their sub-module imports resolve
    # correctly at runtime on a machine without Python installed.
    "email",
    "importlib",
    "encodings",
    "logging",
    "xml",
    "html",
    "http",
    "urllib",
    "multiprocessing",
]

# ---------------------------------------------------------------------------
# Build options
# ---------------------------------------------------------------------------

build_exe_options: dict = {
    "packages": packages,
    "include_files": include_files,
    "zip_include_packages": zip_include_packages,
    "zip_exclude_packages": zip_exclude_packages,
    # Strip test directories, __pycache__, and unused Python bindings.
    "excludes": [
        "tkinter",
        "test",
        "unittest",
        "pydoc",
        # Unused Qt Python bindings — the app uses only Core/Gui/Widgets/Sql/Svg/SvgWidgets.
        "PySide6.QtQml",
        "PySide6.QtQuick",
        "PySide6.QtQuick3D",
        "PySide6.QtQuickWidgets",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
        "PySide6.QtBluetooth",
        "PySide6.QtRemoteObjects",
        "PySide6.QtTextToSpeech",
        "PySide6.QtSerialPort",
        "PySide6.QtWebChannel",
        "PySide6.QtWebSockets",
        "PySide6.QtPdf",
        "PySide6.QtPdfWidgets",
        "PySide6.QtDesigner",
        "PySide6.QtHelp",
        "PySide6.QtDBus",
        "PySide6.QtOpenGL",
        "PySide6.QtOpenGLWidgets",
        "PySide6.QtSensors",
        "PySide6.QtStateMachine",
        "PySide6.QtPositioning",
        "PySide6.QtNfc",
        "PySide6.QtTest",
        # CJK codecs — not needed for English/Western locale app.
        "_codecs_jp",
        "_codecs_cn",
        "_codecs_kr",
        "_codecs_tw",
        "_codecs_iso2022",
        # ----------------------------------------------------------------
        # Dev / build tools — must never be bundled into the frozen app.
        # cx_Freeze packages everything importable from the venv, so these
        # are listed explicitly as a safety net even when the release CI
        # runs with a runtime-only venv (uv sync --no-dev).
        # ----------------------------------------------------------------
        "ruff",
        "pytest",
        "_pytest",
        "pyrefly",
        "pyinstaller",
        "PyInstaller",
        "cx_Freeze",
        "freeze_core",
        "pillow",
        "PIL",
        "zensical",
        "ghp_import",
        "mkdocs",
        "markdown",
        "pymdownx",
        "pygments",
        "jinja2",
        "click",
        "pyyaml",
        "deepmerge",
        "iniconfig",
        "pluggy",
        "altgraph",
        "patchelf",
    ],
    # Exclude shared libraries that are bundled by cx_Freeze's PySide6 hook
    # but are never used by this app (pure QWidgets, SQLite-only, no QML).
    #
    # Scope: only libraries that are actually present in pyside6-essentials.
    # The Addons packages (Multimedia/FFmpeg, Bluetooth, RemoteObjects, TTS,
    # SerialPort, WebChannel, WebSockets, Pdf, Quick3D, ShaderTools) are
    # already absent from pyside6-essentials — no entries needed for them.
    #
    # Each entry covers Linux (.so.6), macOS (.dylib), and Windows (.dll).
    # PySide6 uses the "lib" prefix on all three platforms for Qt libs and
    # for plugin .so/.dylib files (unlike PyQt6 which dropped it on macOS).
    "bin_excludes": [
        # ----------------------------------------------------------------
        # Qt QML / Quick stack (~22 MB on Linux)
        # Present in pyside6-essentials despite the app being pure QWidgets.
        # ----------------------------------------------------------------
        "libQt6Qml.so.6",
        "libQt6Qml.dylib",
        "Qt6Qml.dll",
        "libQt6QmlCompiler.so.6",
        "libQt6QmlCompiler.dylib",
        "Qt6QmlCompiler.dll",
        "libQt6QmlCore.so.6",
        "libQt6QmlCore.dylib",
        "Qt6QmlCore.dll",
        "libQt6QmlLocalStorage.so.6",
        "libQt6QmlLocalStorage.dylib",
        "Qt6QmlLocalStorage.dll",
        "libQt6QmlMeta.so.6",
        "libQt6QmlMeta.dylib",
        "Qt6QmlMeta.dll",
        "libQt6QmlModels.so.6",
        "libQt6QmlModels.dylib",
        "Qt6QmlModels.dll",
        "libQt6QmlNetwork.so.6",
        "libQt6QmlNetwork.dylib",
        "Qt6QmlNetwork.dll",
        "libQt6QmlWorkerScript.so.6",
        "libQt6QmlWorkerScript.dylib",
        "Qt6QmlWorkerScript.dll",
        "libQt6QmlXmlListModel.so.6",
        "libQt6QmlXmlListModel.dylib",
        "Qt6QmlXmlListModel.dll",
        "libQt6Quick.so.6",
        "libQt6Quick.dylib",
        "Qt6Quick.dll",
        "libQt6QuickControls2.so.6",
        "libQt6QuickControls2.dylib",
        "Qt6QuickControls2.dll",
        "libQt6QuickControls2Basic.so.6",
        "libQt6QuickControls2Basic.dylib",
        "Qt6QuickControls2Basic.dll",
        "libQt6QuickControls2BasicStyleImpl.so.6",
        "libQt6QuickControls2BasicStyleImpl.dylib",
        "Qt6QuickControls2BasicStyleImpl.dll",
        "libQt6QuickControls2FluentWinUI3StyleImpl.so.6",
        "libQt6QuickControls2FluentWinUI3StyleImpl.dylib",
        "Qt6QuickControls2FluentWinUI3StyleImpl.dll",
        "libQt6QuickControls2Fusion.so.6",
        "libQt6QuickControls2Fusion.dylib",
        "Qt6QuickControls2Fusion.dll",
        "libQt6QuickControls2FusionStyleImpl.so.6",
        "libQt6QuickControls2FusionStyleImpl.dylib",
        "Qt6QuickControls2FusionStyleImpl.dll",
        "libQt6QuickControls2Imagine.so.6",
        "libQt6QuickControls2Imagine.dylib",
        "Qt6QuickControls2Imagine.dll",
        "libQt6QuickControls2ImagineStyleImpl.so.6",
        "libQt6QuickControls2ImagineStyleImpl.dylib",
        "Qt6QuickControls2ImagineStyleImpl.dll",
        "libQt6QuickControls2Impl.so.6",
        "libQt6QuickControls2Impl.dylib",
        "Qt6QuickControls2Impl.dll",
        "libQt6QuickControls2Material.so.6",
        "libQt6QuickControls2Material.dylib",
        "Qt6QuickControls2Material.dll",
        "libQt6QuickControls2MaterialStyleImpl.so.6",
        "libQt6QuickControls2MaterialStyleImpl.dylib",
        "Qt6QuickControls2MaterialStyleImpl.dll",
        "libQt6QuickControls2Universal.so.6",
        "libQt6QuickControls2Universal.dylib",
        "Qt6QuickControls2Universal.dll",
        "libQt6QuickControls2UniversalStyleImpl.so.6",
        "libQt6QuickControls2UniversalStyleImpl.dylib",
        "Qt6QuickControls2UniversalStyleImpl.dll",
        "libQt6QuickDialogs2.so.6",
        "libQt6QuickDialogs2.dylib",
        "Qt6QuickDialogs2.dll",
        "libQt6QuickDialogs2QuickImpl.so.6",
        "libQt6QuickDialogs2QuickImpl.dylib",
        "Qt6QuickDialogs2QuickImpl.dll",
        "libQt6QuickDialogs2Utils.so.6",
        "libQt6QuickDialogs2Utils.dylib",
        "Qt6QuickDialogs2Utils.dll",
        "libQt6QuickEffects.so.6",
        "libQt6QuickEffects.dylib",
        "Qt6QuickEffects.dll",
        "libQt6QuickLayouts.so.6",
        "libQt6QuickLayouts.dylib",
        "Qt6QuickLayouts.dll",
        "libQt6QuickParticles.so.6",
        "libQt6QuickParticles.dylib",
        "Qt6QuickParticles.dll",
        "libQt6QuickShapes.so.6",
        "libQt6QuickShapes.dylib",
        "Qt6QuickShapes.dll",
        "libQt6QuickTemplates2.so.6",
        "libQt6QuickTemplates2.dylib",
        "Qt6QuickTemplates2.dll",
        "libQt6QuickTest.so.6",
        "libQt6QuickTest.dylib",
        "Qt6QuickTest.dll",
        "libQt6QuickTimeline.so.6",
        "libQt6QuickTimeline.dylib",
        "Qt6QuickTimeline.dll",
        "libQt6QuickTimelineBlendTrees.so.6",
        "libQt6QuickTimelineBlendTrees.dylib",
        "Qt6QuickTimelineBlendTrees.dll",
        "libQt6QuickVectorImage.so.6",
        "libQt6QuickVectorImage.dylib",
        "Qt6QuickVectorImage.dll",
        "libQt6QuickVectorImageGenerator.so.6",
        "libQt6QuickVectorImageGenerator.dylib",
        "Qt6QuickVectorImageGenerator.dll",
        "libQt6QuickVectorImageHelpers.so.6",
        "libQt6QuickVectorImageHelpers.dylib",
        "Qt6QuickVectorImageHelpers.dll",
        "libQt6QuickWidgets.so.6",
        "libQt6QuickWidgets.dylib",
        "Qt6QuickWidgets.dll",
        # ----------------------------------------------------------------
        # Qt Designer (~5.7 MB on Linux)
        # ----------------------------------------------------------------
        "libQt6Designer.so.6",
        "libQt6Designer.dylib",
        "Qt6Designer.dll",
        "libQt6DesignerComponents.so.6",
        "libQt6DesignerComponents.dylib",
        "Qt6DesignerComponents.dll",
        # ----------------------------------------------------------------
        # Unused Qt SQL driver plugins (keep only libqsqlite)
        # ----------------------------------------------------------------
        "libqsqlibase.so",
        "libqsqlibase.dylib",
        "qsqlibase.dll",
        "libqsqlmimer.so",
        "libqsqlmimer.dylib",
        "qsqlmimer.dll",
        "libqsqlmysql.so",
        "libqsqlmysql.dylib",
        "qsqlmysql.dll",
        "libqsqloci.so",
        "libqsqloci.dylib",
        "qsqloci.dll",
        "libqsqlodbc.so",
        "libqsqlodbc.dylib",
        "qsqlodbc.dll",
        "libqsqlpsql.so",
        "libqsqlpsql.dylib",
        "qsqlpsql.dll",
        # ----------------------------------------------------------------
        # Unused Qt image format plugins (keep jpeg, png, gif, svg, ico)
        # ----------------------------------------------------------------
        "libqwebp.so",
        "libqwebp.dylib",
        "qwebp.dll",
        "libqtiff.so",
        "libqtiff.dylib",
        "qtiff.dll",
        "libqicns.so",
        "libqicns.dylib",
        "qicns.dll",
        "libqwbmp.so",
        "libqwbmp.dylib",
        "qwbmp.dll",
        "libqtga.so",
        "libqtga.dylib",
        "qtga.dll",
        "libqpdf.so",
        "libqpdf.dylib",
        "qpdf.dll",
        # ----------------------------------------------------------------
        # TLS backend plugins
        # UpdateChecker uses Python urllib/ssl — not QNetworkAccessManager.
        # If that ever changes, remove these entries and re-test.
        # ----------------------------------------------------------------
        "libqcertonlybackend.so",
        "libqcertonlybackend.dylib",
        "qcertonlybackend.dll",
        "libqopensslbackend.so",
        "libqopensslbackend.dylib",
        "qopensslbackend.dll",
        "libqsecuretransport.dylib",  # macOS built-in TLS backend
        "qschannel.dll",  # Windows Schannel TLS backend
        # ----------------------------------------------------------------
        # Network information plugins (connectivity state; unused)
        # ----------------------------------------------------------------
        "libqconnman.so",
        "libqglib.so",
        "libqnetworkmanager.so",
        # ----------------------------------------------------------------
        # Platform input context plugins (CJK/IBus input methods; unused)
        # ----------------------------------------------------------------
        "libcomposeplatforminputcontextplugin.so",
        "libibusplatforminputcontextplugin.so",
        "libqtvirtualkeyboardplugin.so",
        # ----------------------------------------------------------------
        # Generic input plugins (evdev touch/mouse/keyboard; embedded only)
        # ----------------------------------------------------------------
        "libqevdevkeyboardplugin.so",
        "libqevdevmouseplugin.so",
        "libqevdevtabletplugin.so",
        "libqevdevtouchplugin.so",
        "libqtuiotouchplugin.so",
        # ----------------------------------------------------------------
        # Print support (printing not implemented)
        # ----------------------------------------------------------------
        "libcupsprintersupport.so",
        "libqcocoaprintersupport.dylib",
        # ----------------------------------------------------------------
        # Lottie vector image format plugin (animations; unused)
        # ----------------------------------------------------------------
        "libqlottievectorimage.so",
        "libqlottievectorimage.dylib",
        "qlottievectorimage.dll",
        # ----------------------------------------------------------------
        # System readline (not needed in frozen app)
        # ----------------------------------------------------------------
        "libreadline.so.8",
        "libreadline.dylib",
    ],
    "optimize": 1,
    "build_exe": str(HERE / "dist" / "openstan"),
}

# ---------------------------------------------------------------------------
# Platform installer options
# ---------------------------------------------------------------------------

bdist_msi_options: dict = {
    # This GUID is the permanent identity of the product in the Windows
    # Installer database.  It must NEVER change across releases — changing it
    # would break in-place upgrades and leave ghost entries in Add/Remove
    # Programs.  Generated once with uuid.uuid4() and committed permanently.
    "upgrade_code": "{304AF32E-E6AD-4F92-80DA-F8A9359FE5B5}",
    "add_to_path": False,
    "initial_target_dir": r"[ProgramFilesFolder]\openstan",
    "product_name": "openstan",
    "summary_data": {
        "author": "Jason Farrar",
        "comments": "Open source bank statement analysis and visualization",
        "keywords": "bank statement finance analysis",
    },
}

bdist_mac_options: dict = {
    # bundle_name becomes the .app directory name: openstan.app
    "bundle_name": "openstan",
    # iconfile sets CFBundleIconFile in Info.plist and copies the .icns into
    # Contents/Resources/ so Finder and the Dock display the correct icon.
    "iconfile": str(BUILD_ICONS / "openstan.icns") if BUILD_ICONS.exists() else None,
    # Extra Info.plist keys:
    #   CFBundleIdentifier — reverse-DNS identifier required by macOS / Gatekeeper
    #   NSHighResolutionCapable — opt in to Retina (HiDPI) rendering
    #   NSRequiresAquaSystemAppearance — allow the app to follow dark mode
    #   CFBundleShortVersionString — surface the version in Finder's Get Info
    "plist_items": [
        ("CFBundleIdentifier", "org.openstan.app"),
        # CFBundleName and CFBundleDisplayName must be set explicitly so that
        # the macOS dock, cmd-tab switcher, and menu bar show "openstan" rather
        # than falling back to the cx_Freeze Python runtime executable name
        # ("python3.14").  CFBundleDisplayName takes priority over CFBundleName
        # in all system UI contexts.
        ("CFBundleName", "openstan"),
        ("CFBundleDisplayName", "openstan"),
        ("NSHighResolutionCapable", True),
        ("NSRequiresAquaSystemAppearance", False),
        ("CFBundleShortVersionString", _version),
    ],
}

bdist_dmg_options: dict = {
    "volume_label": "openstan",
    "applications_shortcut": True,
}

# Linux packaging (.deb / .rpm) is handled entirely by fpm in the CI workflow.
# No bdist_rpm or bdist_deb options are needed here.

# ---------------------------------------------------------------------------
# Executable definition
# ---------------------------------------------------------------------------
# On Windows two Executable entries are needed to create both a Desktop and a
# Start Menu shortcut via the bdist_msi shortcut mechanism.  On macOS and
# Linux only one entry is used — duplicate target_name entries cause
# bdist_mac to fail with "can't move: not a regular file".

if sys.platform == "win32":
    executables: list[Executable] = [
        Executable(
            script=str(SRC_PKG / "__main__.py"),
            target_name="openstan",
            base=base,
            icon=icon_path,
            shortcut_name="openstan",
            shortcut_dir="DesktopFolder",
        ),
        Executable(
            script=str(SRC_PKG / "__main__.py"),
            target_name="openstan",
            base=base,
            icon=icon_path,
            shortcut_name="openstan",
            shortcut_dir="ProgramMenuFolder",
        ),
    ]
else:
    executables = [
        Executable(
            script=str(SRC_PKG / "__main__.py"),
            target_name="openstan",
            base=base,
            icon=icon_path,
        ),
    ]

# ---------------------------------------------------------------------------
# setup() call
# ---------------------------------------------------------------------------

setup(
    name="openstan",
    version=_version,
    description="Open source bank statement analysis and visualization",
    author="Jason Farrar",
    author_email="stillwaters.technology@gmail.com",
    url="https://openstan.org",
    options={
        "build_exe": build_exe_options,
        "bdist_mac": bdist_mac_options,
        "bdist_msi": bdist_msi_options,
        "bdist_dmg": bdist_dmg_options,
    },
    executables=executables,
)

# ---------------------------------------------------------------------------
# Post-build cleanup: remove the Qt QML directory tree
# ---------------------------------------------------------------------------
# cx_Freeze's PySide6 hook copies lib/PySide6/Qt6/qml/ as a directory, so it is
# not caught by bin_excludes.  The app is pure QWidgets — QML is never used.
# This runs on all platforms; it is guarded by .exists() so it is safe if
# cx_Freeze's hook behaviour changes in a future release.

_qml_dir = Path(build_exe_options["build_exe"]) / "lib" / "PySide6" / "Qt6" / "qml"
if _qml_dir.exists():
    shutil.rmtree(_qml_dir)
    print(f"Post-build: removed unused QML directory tree ({_qml_dir})")

# bank_statement_parser bundles a test_data/ tree (anonymised PDF fixtures for
# its own test suite).  That data is not needed at runtime and should not be
# shipped in the production installer.  Strip it here so it never reaches the
# WiX harvester.
_bsp_test_data = (
    Path(build_exe_options["build_exe"]) / "lib" / "bank_statement_parser" / "test_data"
)
if _bsp_test_data.exists():
    shutil.rmtree(_bsp_test_data)
    print(f"Post-build: removed BSP test_data directory ({_bsp_test_data})")
